language: go
dist: xenial
sudo: true

matrix:
  include:
  - os: linux
    env:
    - GOOS=linux
    - GOARCH=amd64
    - HOST_OS=linux
    go: "1.13"
  - os: linux
    env:
    - GOOS=linux
    - GOARCH=386
    - HOST_OS=linux
    go: "1.13"
  - os: linux
    env:
    - GOOS=linux
    - GOARCH=arm64
    - HOST_OS=linux
    go: "1.13"
  - os: linux
    env:
    - GOOS=linux
    - GOARCH=arm
    - HOST_OS=linux
    go: "1.13"
  - os: linux
    env:
    - GOOS=windows
    - GOARCH=amd64
    - HOST_OS=linux
    go: "1.13"
  - os: linux
    env:
    - GOOS=windows
    - GOARCH=386
    - HOST_OS=linux
    go: "1.13"
  - os: osx
    env:
    - GOOS=darwin
    - GOARCH=amd64
    - HOST_OS=darwin
    go: "1.13"

before_install:
- git fetch --tags
- GOARCH=amd64 GOOS=$HOSTOS go get github.com/mattn/goveralls
- GOARCH=amd64 GOOS=$HOSTOS go get github.com/GeertJohan/go.rice/rice
script:
- go get ./...
- ./ci/test.sh
- GOARCH=amd64 GOOS=$HOSTOS make vue_production
- GOARCH=amd64 GOOS=$HOSTOS make generate
- make dist
# - file remoteSwitch
before_deploy:
- ./ci/pack.sh
deploy:
  provider: releases
  file_glob: true
  file: remoteSwitch-v$TRAVIS_TAG-$GOOS-$GOARCH.*
  skip_cleanup: true
  on:
    repo: dh1tw/remoteSwitch
    tags: true
    draft: true